const os = require ('os');
console.log(`Platform: ${os.platform}`);
console.log(`Architecture: ${os.arch}`);
console.log(`Release: ${os.release}`);
console.log(`Free Memory: ${os.freemem}`);
console.log(`Total Memory: ${os.totalmem()}`);
console.log(`Version: ${os.version}`);
console.log(`Type: ${os.type}`);
console.log(`Home Directory: ${os.homedir}`);
console.log(`CPU: ${os.cpus()}`);